spring.config.activate.on-profile=prod
spring.datasource.url=jdbc:postgresql://://amazonaws.com
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}
aws.s3.bucket-name=todo-bucket-93085605929679205
aws.s3.region=eu-north-1
